extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - prettier/react
  - react-app
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/errors
  - plugin:import/typescript
plugins:
  - "@typescript-eslint"
  - import
settings:
  import/resolver:
    node:
      paths: ["src"]
      extensions: [".js", ".jsx", ".ts", ".tsx"]
rules:
  import/order: ["warn", { "alphabetize": { "order": "asc" } }]
ignorePatterns:
  - /build
