root: true
env:
  node: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended
  - prettier/react
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/recommended
  - plugin:import/typescript
plugins:
  - '@typescript-eslint'
  - import
settings:
  import/resolver:
    node:
      paths: ['src']
      extensions: ['.js', '.jsx', '.ts', '.tsx']
  react:
    version: detect
rules:
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
      argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  import/order: ['warn', { 'alphabetize': { 'order': 'asc' } }]
  react/react-in-jsx-scope: off
ignorePatterns:
  - /build
  - /dist
  - /src/generated
