query eventSet($id: ID!) {
  eventSet(id: $id) {
    id
    operation
    createdAt
    bookEvents {
      eventId
      eventSetId
      operation
      bookId
      title
      authorIds
      isbn
      read
      owned
      priority
      format
      store
      bookCreatedAt
      bookUpdatedAt
      changedAt
      extra
    }
    authorEvents {
      eventId
      eventSetId
      operation
      authorId
      name
      yomi
      authorCreatedAt
      authorUpdatedAt
      changedAt
      extra
    }
  }
}
