name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update package.json
        run: |
          tag=${{ steps.release_drafter.outputs.tag_name }}
          npm --no-git-tag-version version ${tag#v}
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version
